### ISSUE TITLE
README seems to have wrong syntax compared to ansible-docs

### ISSUE THREAD

**Issue by balaji-dutt** [totaldebug/ansible-collection-hassio_cli#4]
I'm currently setting up a Home Assistant Host and wanted to use your Ansible Collection to manage the addons. However, following just the README results in an error:

## Expected behavior
* Install the collection `ansible-galaxy install totaldebug.hassio_cli`
* Create a simple playbook:
```yml
- hosts: ha-host
# The following is from the README
  - name: Test HASSOS Addon
      totaldebug.hassio_cli.hassio_addon:
        state: present
        name: core_samba
```

## Current behavior
Running the playbook results in the following error:
``` shell
$ ansible-playbook ha-host.yml -i inventory.yml -v
ERROR! couldn't resolve module/action 'totaldebug.hassio_cli.hassio_addon'. This often indicates a misspelling, missing collection, or incorrect module path.
```

## Possible reasons and solutions
Looking through ansible-docs suggests there's a typo in the README:
```shell
$ ansible-doc -l | grep hassio
totaldebug.hassio_cli.hassio_addon_repos                                       Manage Home Assistant (HassIO) addon reposito...
totaldebug.hassio_cli.hassio_addons                                            Manage Home Assistant (HassIO) ad...
totaldebug.hassio_cli.hassio_host                                              Manage Home Assistant (HassIO) ...
totaldebug.hassio_cli.hassio_snapshot                                          Manage Home Assistant (HassIO) snap...
```
Note that the module is listed as **.hassio_addons** and not *.hassio_addon* (plural vs singular) as in the README.

## Context
* Failed to install a module following the README 

## Checklist

- [x] I searched the current issues and the issue is not known.
- [x] I searched the troubleshooting and there's no fix available for this bug.
- [x] I searched on Google, YouTube, Reddit and there's no fix.
- [x] I am mostly sure that the problem is related to the code and isn't my fault.

**Comment by marksie1988** [comment]
Thanks, yes correct it should be `hassio_addons`

Thanks for pointing this out, I'll fix it as soon as I'm on my computer 🙂

**Comment by marksie1988** [comment]
It's also worth noting there is an issue with using the hassio_addon_repo module, #3 home assistant although is able to add to all the backend files doesn't update the UI which stops it functioning correctly.

**Comment by balaji-dutt** [comment]
> It's also worth noting there is an issue with using the hassio_addon_repo module, #3 home assistant although is able to add to all the backend files doesn't update the UI which stops it functioning correctly.

Yes I did notice #3 when I came across this repo. I don't have any need to add a custom repo (yet) but will keep this issue in mind!
