### ISSUE TITLE
Add support for HassOS and Hass core to be updated

### ISSUE THREAD

**Issue by mjkl-gh** [totaldebug/ansible-collection-hassio_cli#6]
### Feature

I would like to also update the Hass Core container and the HassOS operating system using this ansible collection

### Use Case

Update Home assistant using a single ansible script

### Plan to implement

Will submit PR

**Comment by mjkl-gh** [comment]
Closed because #5 was merged

**Comment by marksie1988** [comment]
I will need to add a tag for a release which I can do later today as I'm out at the moment
